# Benchmark configurations
module: multimodal  # required
mode: local  # required
benchmark_name: ag_bench  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"
# METRICS_BUCKET: autogluon-benchmark-metrics  # optional, required only if you want to upload metrics to S3

# Multimodal specific
framework: AutoGluon_stable
# git_uri#branch: https://github.com/autogluon/autogluon#master  # required
dataset_name: 
  stanfordcars  # required
custom_dataloader:
    dataloader_file: sample_configs/dataloaders/vision_dataloader.py   # relative path to WORKDIR
    class_name: VisionDataLoaer
    dataset_config_file: sample_configs/dataloaders/vision_datasets.yaml 
