# Benchmark configurations
module: multimodal  # required
mode: local  # required
benchmark_name: ag_bench  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"
# METRICS_BUCKET: autogluon-benchmark-metrics  # optional, required only if you want to upload metrics to S3

# Multimodal specific
git_uri#branch: https://github.com/autogluon/autogluon#master  # required
dataset_name: melbourne_airbnb  # required
presets: medium_quality  # optional
hyperparameters:  # optional
  optimization.learning_rate: 0.0005
  optimization.max_epochs: 5
time_limit: 10  # optional
