module: autokeras  # required, choise of 'multimodal' pr 'autokeras'
mode: local  # required
benchmark_name: ag_bench_text_tabular  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"

constraint: g4_12x  # configurations will override cdk_context, options can be found at resources/multimodal_constraints.yaml, custom constraint is also supported, default: test
framework:   # framework options can be found at resources/multimodal_frameworks.yaml, custom framework is also supported.
  AutoGluon_best_master
  # autokeras_master
  # ablation_base
  # ablation_greedy_soup
  # ablation_gradient_clip
  # ablation_warmup_steps
  # ablation_cosine_decay
  # ablation_weight_decay
  # ablation_lr_decay
dataset_name: airbnb 
custom_dataloader:
    dataloader_file: sample_configs/dataloaders/text_tabular_dataloader.py   # relative path to WORKDIR
    class_name: TextTabularDataLoader
    dataset_config_file: sample_configs/dataloaders/paper_text_tabular_datasets.yaml 
custom_resource_dir: sample_configs/resources/

