# Infra configurations
cdk_context:  # AWS infra configs used to setup AWS Batch environment with AWS CDK
  CDK_DEPLOY_ACCOUNT: dummy  # required, update with your AWS account
  CDK_DEPLOY_REGION: dummy  # required, update with your desired region
  PREFIX: ag-bench  # Used to identify infra resources created, optional, default = ag-bench
  METRICS_BUCKET: autogluon-benchmark-metrics  # required, has to be a globally unique name
  # DATA_BUCKET: existing-s3-bucket  # optional, S3 bucket to download your private datasets
  # MAX_MACHINE_NUM: 20   # optional
  # BLOCK_DEVICE_VOLUME: 100   # optional
  # RESERVED_MEMORY_SIZE: 15000  # optional
  # INSTANCE: g4dn.2xlarge  # optional

# Benchmark configurations
module: tabular  # required
mode: aws  # required
benchmark_name: ag_bench  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"

module_configs:
  # Tabular specific
  # You can refer to AMLB (https://github.com/openml/automlbenchmark#quickstart) for more details
  tabular:
    git_uri#branch:  # required, can be any AMLB custom fork and branch, only one value allowed
      - https://github.com/openml/automlbenchmark.git#master
    framework:  # required, only one value allowed
      - AutoGluon:stable
    amlb_benchmark:  # required, each benchmark contains a list of datasets, can be subsetted by amlb_task below
      - small
    amlb_task:  # optional, value of each key is a subset of dataset names in each 'amlb_benchmark'
      small:
        - credit-g
        - vehicle
    amlb_constraint:  # optional, only one value allowed
      - test
    # fold_to_run:  # optional, capped by `folds` in amlb_constraint
    #   small:
    #     credit-g:
    #       - 3
    #       - 6
    # amlb_user_dir:  # optional, local/s3 path where all the amlb customizations are stored, only one value allowed
    #   - sample_configs/amlb_configs
