# Infra configurations
cdk_context:  # AWS infra configs used to setup AWS Batch environment with AWS CDK
  CDK_DEPLOY_ACCOUNT: dummy  # required, update with your AWS account
  CDK_DEPLOY_REGION: dummy  # required, update with your desired region
  PREFIX: ag-bench  # Used to identify infra resources created, optional, default = ag-bench
  METRICS_BUCKET: autogluon-benchmark-metrics  # required, has to be a globally unique name
  # DATA_BUCKET: existing-s3-bucket  # optional, S3 bucket to download your private datasets
  # MAX_MACHINE_NUM: 20   # optional, default 20
  # BLOCK_DEVICE_VOLUME: 100   # optional, default 100GB
  # RESERVED_MEMORY_SIZE: 15000  # optional, default 15000MB
  # INSTANCE: g4dn.2xlarge  # optional, default g4dn.2xlarge
  # TIME_LIMIT: 3600  # optional, EC2 timeout, default 3600s
  # VPC_NAME: existing-vpc-name  # optional

# Benchmark configurations
module: timeseries  # required
mode: aws  # required
benchmark_name: ag_bench  # required
root_dir: ag_bench_runs  # optional, default = "ag_bench_runs"

git_uri#branch:  # required, can be any AMLB custom fork and branch, only one value allowed
  https://github.com/openml/automlbenchmark.git#master
framework:  # required, only one value allowed
  AutoGluon_dev:example
amlb_constraint:  # optional, only one value allowed, default: test
  test
amlb_benchmark:  # required, a list of amlb benchmarks to run, ref: https://github.com/openml/automlbenchmark/tree/master/resources/benchmarks
  - timeseries_test
amlb_task:  # optional, value of each key is a subset of dataset names in each 'amlb_benchmark', ref: https://github.com/openml/automlbenchmark/blob/master/resources/benchmarks/small.yaml
  timeseries_test:
    - m4_hourly_2
# fold_to_run:  # optional, capped by `folds` in amlb_constraint, ref: https://github.com/openml/automlbenchmark/blob/master/resources/constraints.yaml
amlb_user_dir:  # optional, local/s3 path where all the amlb customizations are stored, only one value allowed
  sample_configs/amlb_configs
