git_user: suzhoum
git_branch: master
module: multimodal
problem_type: classification
data_path: MNIST
label: label
presets: best_quality
metrics: ["acc"]
time_limit: 10
hyperparameters:
    optimization.max_epochs: 10
    env.per_gpu_batch_size: 32
    optimization.top_k_average_method: best
    
infra_args:
    STACK_NAME_PREFIX: automm-test,
    STACK_NAME_TAG: benchmark,
    STATIC_RESOURCE_STACK_NAME: automm-test-static-resource-stack,
    BATCH_STACK_NAME: automm-test-batch-stack,
    EXPERIMENT_TABLE: automm-test-bench-table,
    MODEL_BUCKET: automm-test-models,
    DATA_BUCKET: automl-mm-bench,
    INSTANCE_TYPES: [
        "g5.4xlarge"
    ],
    DOCKER_PATH: ./automm_batch_job,
    COMPUTE_ENV_MAXV_CPUS: 320,
    CONTAINER_GPU: 1,
    CONTAINER_VCPU: 16,
    BLOCK_DEVICE_VOLUME: 200,
    LAMBDA_FUNCTION_NAME: automm-test-batch-job-function,
    VPC_NAME: automm-ap-bench-batch-stack/automm-ap-bench-vpc,